<?php
/*
 * This template does not output anything but a specific partial output
 */

// this is the standard template data
$templateData = array(
                'title' => $this->title,
                'resourceUri' => $this->resourceUri,
                'description' => $this->description,
                'descriptionHelper' => $this->descriptionHelper
        );

if (isset($this->description['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'])) {
    $types = array ();
    foreach ($this->description['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'] as $property) {
        if ((isset($property['value'])) && (Erfurt_Uri::check($property['value']))) {
            $types[$property['value']] = true;
        }
    }

    switch ($types) {
        case (isset($types['http://purl.org/net/faunistics#Location'])):
        case (isset($types['http://purl.org/net/faunistics#Area'])):
            echo $this->partial( 'local/types/checklist.phtml', $templateData);
            break;
        case (isset($types['http://purl.org/net/faunistics#Species'])):
            echo $this->partial( 'local/types/species.phtml', $templateData);
            break;
        case (isset($types['http://purl.org/net/faunistics#Publication'])):
            echo $this->partial( 'local/types/publication.phtml', $templateData);
            break;
        case (isset($types['http://purl.org/net/faunistics#CitedRecord'])):
        case (isset($types['http://purl.org/net/faunistics#OriginalRecord'])):
            echo $this->partial( 'local/types/record.phtml', $templateData);
            break;
        case ($this->resourceUri == 'http://db.caucasus-spiders.info/Document/Literature'):
            echo $this->partial( 'local/types/literature.phtml', $templateData);
            break;
        default:
            // no specific template found
            echo $this->partial( 'local/default.phtml', $templateData);
            break;
    }
}
?>
