<div class="box">
    <h2>
        <?php echo $this->title ?>
    </h2>
    <?php echo $this->literal(array('tag' => 'div', 'class' => 'block')); // uses default content properties ?>

<?php
$publications = '
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX faun: <http://purl.org/net/faunistics#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
SELECT DISTINCT ?resourceUri ?pubLabel ?pubDescription ?pubComment
WHERE {
  ?resourceUri a faun:Publication.
  ?resourceUri dc:description ?pubDescription.
  ?resourceUri rdfs:label ?pubLabel.
  OPTIONAL {
  ?resourceUri rdfs:comment ?pubComment.
  }
}
ASC(?pubDescription)
LIMIT 10000
';
?>
    <div class="block">
        <table class="checklist">
            <thead>
                <tr>
                    <th>Referenz</th>
                    <th>Publication</th>
                    <th>Comment</th>
                </tr>
            </thead>
            <tbody>
                <?php echo $this->querylist(
                        $publications,
                        'local/types/literature-row.phtml',
                        array('isResult' => true) ); ?>
            </tbody>
        </table>
    </div>
</div>
